fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive.git"
      ref:  "v1.3.0"
  symlinks:
    aerospike: "#{source_dir}"
