---
language: ruby
bundler_args: --without development system_tests
before_install:
  - gem update --system
script: 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 2.3.8
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.8
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.8
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.8
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=rubocop
  - rvm: 2.5.8
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.5.8
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=rubocop
